u8int memread(u16int);
void memwrite(u16int, u8int);
int step(void);
void ppustep(void);
void disasm(u16int);
void interrupt(u8int);
void message(char *, ...);
void flushram(void);
void savestate(char *);
void loadstate(char *);
void initaudio(void);