u8int memread(u16int);
void memwrite(u16int, u8int);
void addevent(Event *, int);
void delevent(Event *);
void popevent(void);
void eventinit(void);
void meminit(void);
void reset(void);
int step(void);
void ppusync(void);
void ppuinit(void);
void flush(void);
void timertac(u8int, int);
void timerset(void);
void writeback(void);
void loadstate(char *);
void savestate(char *);
void flushback(void);
void getvars(Var *);
void putvars(Var *);
void memload(void);
int dmastep(void);
void audioinit(void);
int audioout(void);
void sndwrite(u8int, u8int);
u8int waveread(u8int);
void wavewrite(u8int, u8int);
u8int timread(void);
