u32int memread(u32int, int, int);
void memwrite(u32int, u32int, int);
extern int (*step)(void);
void reset(void);
void memreset(void);
void setif(u16int);
void ppustep(void);
void timerstep(int t);
void flush(void);
int dmastep(void);
void dmastart(int);
void flushback(void);
void writeback(void);
void eventinit(void);
void popevent(void);
u16int timerget(int);
void timerset(int, u16int);
void addevent(Event *, int);
void ppuwrite(u16int, u16int);
void fifoput(int, u32int);
void soundcnth(u16int);
void soundbias(u16int);
void audioinit(void);
int audioout(void);
void sndwrite(u16int, u16int);
void loadstate(char *);
void savestate(char *);
void cpuload(void);
void gpioident(void);
void gpiowdata(u32int);
void gpiowdir(u32int);
void gpiowcontrol(u32int);
u32int gpiordata(void);
u32int gpiordir(void);
u32int gpiorcontrol(void);
