</$objtype/mkfile

DIRS=port $CPUS

default:V:	all

install all:V:
	for(i in port $objtype)@{
		echo $i
		cd $i
		mk $MKFLAGS $target
	}

clean:V:
	rm -f [$OS].* *.[$OS]
	for(i in $DIRS)@{
		echo $i
		cd $i
		mk $MKFLAGS $target
	}

nuke:V: clean
	rm -f /$objtype/lib/ape/libsec.a

installall:V:
	for(objtype in $CPUS) mk $MKFLAGS install

everything:V:
	rm -f */*.[$OS]
	for(objtype in $CPUS)@{
		echo $objtype
		mk $MKFLAGS install
	}
	rm -f */*.[$OS]

APE=/sys/src/ape
<$APE/config

$O.tlsclient: tlsclient.c
	$CC -o $target $CFLAGS -D_POSIX_SOURCE -D_PLAN9_SOURCE -D_NET_EXTENSION tlsclient.c
