APE=/sys/src/ape
<$APE/config

LIB=/$objtype/lib/ape/libsec.a
FILES=\
	md5block\
	sha1block\

HFILES=/sys/include/ape/libsec.h

SFILES=${FILES:%=%.s}

OFILES=${FILES:%=%.$O}

UPDATE=mkfile\
	$HFILES\
	$SFILES\

</sys/src/cmd/mksyslib

%.$O:	/sys/src/libsec/$objtype/%.s
	$AS $AFLAGS /sys/src/libsec/$objtype/$stem.s
