</$objtype/mkfile

LIB=libcommon.a$O
OFILES=\
	aux.$O\
	become.$O\
	config.$O\
	folder.$O\
	flags.$O\
	fmt.$O\
	libsys.$O\
	process.$O\

HFILES=common.h\
	sys.h\

CLEANFILES=$LIB

</sys/src/cmd/mklib

nuke:V:
	mk clean
	rm -f libcommon.a[$OS]
