APE=/sys/src/ape
<$APE/config

LIB=../libpython.a$O

OFILES=\
	acceler.$O\
	bitset.$O\
	firstsets.$O\
	grammar1.$O\
	listnode.$O\
	metagrammar.$O\
	myreadline.$O\
	node.$O\
	parser.$O\
	parsetok.$O\
	tokenizer.$O\

CLEANFILES=`{echo pgen.^($CPUS)}

</sys/src/cmd/mksyslib

CFLAGS=-c -I.. -I../Include -DT$objtype -DPy_BUILD_CORE -DNDEBUG

obmalloc.$O:	../Objects/obmalloc.c
	$CC $CFLAGS $prereq

mysnprintf.$O:	../Python/mysnprintf.c
	$CC $CFLAGS $prereq

parsetok.$O:	../Include/graminit.h

PGENOFILES=\
	acceler.$O\
	bitset.$O\
	firstsets.$O\
	grammar.$O\
	grammar1.$O\
	listnode.$O\
	metagrammar.$O\
	node.$O\
	parser.$O\
	parsetok.$O\
	pgen.$O\
	pgenmain.$O\
	printgrammar.$O\
	tokenizer_pgen.$O\
	obmalloc.$O\
	mysnprintf.$O\

pgen.$objtype:	$PGENOFILES
	$LD -o $target $prereq

