URL=https://github.com/raspberrypi/firmware/raw/master/boot
FILES=bootcode.bin fixup_cd.dat start_cd.elf fixup4cd.dat start4cd.elf bcm2711-rpi-4-b.dtb LICENCE.broadcom

all:V:	$FILES

clean:V:
	rm -f $FILES

$FILES:
	for(i in $target){
		hget -o $i $URL/$i
	}
