</$objtype/mkfile

TARG=exsort\
	format\
	mbr\
	mkext\
	mkfs\
	partfs\
	cryptsetup\

DIRS=\
	9660\
	prep\
	smart\
#	sacfs\
	vblade\

OFILES=

BIN=/$objtype/bin/disk

UPDATE=\
	mkfile\
	${TARG:%=%.c}\
	/sys/man/8/prep\
	/sys/man/8/mkfs\
	${TARG:%=/386/bin/disk/%}\

</sys/src/cmd/mkmany

all:V:	all-dirs

install:V:	install-dirs

clean:V:	clean-dirs

nuke:V:		nuke-dirs

installall:V:	installall-dirs

%-dirs:V:
	for(i in $DIRS) @{
		cd $i
		mk $MKFLAGS $stem
	}

$O.format: /$objtype/lib/libdisk.a
