</$objtype/mkfile

LIB=/$objtype/lib/libmemdraw.a
OFILES=\
	alloc.$O\
	arc.$O\
	cload.$O\
	cmap.$O\
	cread.$O\
	defont.$O\
	draw.$O\
	ellipse.$O\
	fillpoly.$O\
	hwdraw.$O\
	line.$O\
	load.$O\
	openmemsubfont.$O\
	poly.$O\
	read.$O\
	string.$O\
	subfont.$O\
	unload.$O\
	write.$O\
	warp.$O\

</sys/src/cmd/mksyslib

alloc.$O draw.$O: /sys/include/pool.h
