</$objtype/mkfile

LIB=/$objtype/lib/libmemdraw.a
OFILES=\
	alloc.$O\
	arc.$O\
	cload.$O\
	cmap.$O\
	cread.$O\
	defont.$O\
	draw.$O\
	ellipse.$O\
	fillpoly.$O\
	hwdraw.$O\
	line.$O\
	load.$O\
	openmemsubfont.$O\
	poly.$O\
	read.$O\
	string.$O\
	subfont.$O\
	unload.$O\
	write.$O\

UPDATE=\
	mkfile\
	$HFILES\
	${OFILES:%.$O=%.c}\

</sys/src/cmd/mksyslib

$O.drawtest: drawtest.$O $LIB
	$LD -o $target $prereq
 
$O.arctest: arctest.$O draw.$O arc.$O $LIB
	$LD -o $target $prereq
