</$objtype/mkfile

TARG=mothra
LIB=libpanel/libpanel.$O.a 
CFILES= \
	snoop.c \
	forms.c \
	getpix.c \
	html.syntax.c \
	mothra.c \
	rdhtml.c \
	url.c \

OFILES=${CFILES:%.c=%.$O}
HFILES=mothra.h html.h libpanel/panel.h libpanel/rtext.h
BIN=/$objtype/bin
</sys/src/cmd/mkone

CFLAGS=-FTVw -Ilibpanel

$LIB:V:
	cd libpanel
	mk

clean nuke:V:
	@{ cd libpanel; mk $target }
	rm -f *.[$OS] [$OS].out $TARG
