</$objtype/mkfile
<../config

TARG=mkplist zuke
CFLAGS=$CFLAGS -I../libtags

HFILES=\
	plist.h\
	icy.h\
	../libtags/tags.h\

default:V: all

$O.mkplist: icy.$O plist.$O mkplist.$O

$O.zuke: icy.$O plist.$O zuke.$O

</sys/src/cmd/mkmany
