u8int	memread(u32int);
void	memwrite(u32int, u8int);
void	cpureset(void);
int	cpustep(void);
void	spcreset(void);
int	spcstep(void);
void	spctimerstep(void);
int	dmastep(void);
void	ppustep(void);
void	memreset(void);
int	hdmastep(void);
void	flush(void);
void	message(char *, ...);
void	dspstep(void);
u8int	dspread(u8int);
void	dspwrite(u8int, u8int);
void	dspreset(void);
void	audioinit(void);
int	audioout(void);
void	flushram(void);
void	loadstate(char *);
void	savestate(char *);
void	dspsave(void);
void	dspload(void);
int	get8(void);
int	get16(void);
int	get32(void);
void	put8(u8int);
void	put16(u16int);
void	put32(u32int);
