</$objtype/mkfile

BIN=/$objtype/bin/games
TARG=snes
OFILES=\
	cpu.$O\
	snes.$O\
	mem.$O\
	ppu.$O\
	spc.$O\
	dsp.$O\
	state.$O\
	eui.$O\

HFILES=dat.h fns.h

</sys/src/cmd/mkone
eui.$O: ../eui.c
	$CC $CFLAGS ../eui.c
