#!/bin/python
#
# mercurial - scalable distributed SCM
#
# Copyright 2005-2007 Matt Mackall <mpm@selenic.com>
#
# This software may be used and distributed according to the terms of the
# GNU General Public License version 2, incorporated herein by reference.

# enable importing on demand to reduce startup time
try:
    from mercurial import demandimport; demandimport.enable()
except ImportError:
    import sys
    sys.stderr.write("abort: couldn't find mercurial libraries in [%s]\n" %
                     ' '.join(sys.path))
    sys.stderr.write("(check your install and PYTHONPATH)\n")
    sys.exit(-1)

import sys
import mercurial.util
import mercurial.dispatch

if sys.platform == 'plan9':
    def p9sys_rcpath():
        return ['/sys/lib/hgrc']

    def p9usr_rcpath():
        import os
        return [os.environ['home']+'/lib/hgrc']

    import mercurial.posix
    mercurial.posix.system_rcpath = p9sys_rcpath
    mercurial.posix.user_rcpath = p9usr_rcpath

for fp in (sys.stdin, sys.stdout, sys.stderr):
    mercurial.util.set_binary(fp)

mercurial.dispatch.run()
