</$objtype/mkfile

TARG=8c
OFILES=\
	cgen.$O\
	cgen64.$O\
	div.$O\
	enam.$O\
	list.$O\
	machcap.$O\
	mul.$O\
	peep.$O\
	pgen.$O\
	pswt.$O\
	reg.$O\
	sgen.$O\
	swt.$O\
	txt.$O\

HFILES=\
	gc.h\
	8.out.h\
	../cc/cc.h\

LIB=../cc/cc.a$O

BIN=/$objtype/bin
</sys/src/cmd/mkone

$LIB:	../cc/cc.h
	cd ../cc
	mk install


%.$O: ../cc/%.c
	$CC $CFLAGS ../cc/$stem.c


enam.c:	8.out.h
	rc mkenam
