</$objtype/mkfile
<../mkupas

TARG=aliasmail

OFILES=aliasmail.$O\

LIB=../common/libcommon.a$O\

HFILES=../common/common.h\
	 ../common/sys.h\


UPDATE=\
	mkfile\
	$HFILES\
	${OFILES:%.$O=%.c}\

</sys/src/cmd/mkone
CFLAGS=$CFLAGS -I../common
