ARCH=\
	bcm\
	bcm64\
	cycv\
	kw\
#	power arch:\
#	mtx\
	omap\
	pc\
	pc64\
#	power arch:\
#	ppc\
	sgi\
	teg2\
	xen\
	zynq\

all:V:
	for(i in $ARCH)@{
		cd $i
		mk
	}

installall install:V:
	for(i in $ARCH) @{
		cd $i
		mk install
	}

clean:V:
	for(i in $ARCH) @{
		cd $i
		mk clean
	}
