</$objtype/mkfile

LIBS=libogg libvorbis libFLAC
PROGS=pcmconv oggdec oggenc mp3dec mp3enc flacdec wavdec sundec mixfs
#libs must be made first
DIRS=$LIBS $PROGS

UPDATE=\
	mkfile\

all:V:
	for (i in $DIRS) @{
		cd $i
		mk all
	}

clean:V:
	for (i in $DIRS) @{
		cd $i
		mk clean
	}

nuke:V:
	for (i in $LIBS) @{
		cd $i
		mk nuke
	}
	for (i in $PROGS) @{
		cd $i
		mk clean
	}

install:V:
	mkdir -p $BIN
	for (i in $DIRS) @{
		cd $i
		mk install
	}

installall:V:
	for (i in $DIRS) @{
		cd $i
		mk installall
	}
	for (i in $DIRS) @{
		cd $i
		mk clean
	}

safeinstallall:V:
	for (i in $LIBS) @{
		cd $i
		mk installall
	}
	for (i in $PROGS) @{
		cd $i
		mk safeinstallall
	}
	for (i in $DIRS) @{
		cd $i
		mk clean
	}
