</$objtype/mkfile
<../mkupas

TARG=marshal

LIB=../common/libcommon.a$O\

HFILES=	../common/common.h\

OFILES= marshal.$O

UPDATE=\
	mkfile\
	$HFILES\
	${OFILES:%.$O=%.c}\
	
</sys/src/cmd/mkone
CFLAGS=$CFLAGS -I../common

