</$objtype/mkfile

LIBS=common
PROGS=\
	Mail\
	alias\
	bayes\
	binscripts\
	filterkit\
	fs\
	imap4d\
	marshal\
	ml\
	ned\
	pop3\
	q\
	scanmail\
	send\
	smtp\
	spf\
	unesc\
	vf\

#libs must be made first
DIRS=$LIBS $PROGS

UPDATE=\
	mkfile\
	/sys/man/1/mail\

all:V:
	for (i in $DIRS) @{
		cd $i
		mk all
	}

clean:V:
	for (i in $DIRS) @{
		cd $i
		mk clean
	}

nuke:V:
	for (i in $LIBS) @{
		cd $i
		mk nuke
	}
	for (i in $PROGS) @{
		cd $i
		mk clean
	}

install:V:
	for (i in $DIRS) @{
		cd $i
		mk install
	}

installall:V:
	for (i in $DIRS) @{
		cd $i
		mk installall
	}
	for (i in $DIRS) @{
		cd $i
		mk clean
	}

safeinstallall:V:
	for (i in $LIBS) @{
		cd $i
		mk installall
	}
	for (i in $PROGS) @{
		cd $i
		mk safeinstallall
	}
	for (i in $DIRS) @{
		cd $i
		mk clean
	}

update:V:
	update $UPDATEFLAGS $UPDATE
	for (i in $DIRS) @{
		cd $i
		echo '>>>>>>>>>>' `{pwd} '<<<<<<<<<<<'
		mk $MKFLAGS 'UPDATEFLAGS='$"UPDATEFLAGS update
	}
