</$objtype/mkfile

LIBS=common
PROGS=\
	Mail\
	alias\
	bayes\
	binscripts\
	filterkit\
	fs\
	imap4d\
	marshal\
	ml\
	ned\
	pop3\
	q\
	scanmail\
	send\
	smtp\
	spf\
	unesc\
	vf\

#libs must be made first
DIRS=$LIBS $PROGS

all install installall clean nuke:V:
	for (i in $DIRS) @{
		cd $i
		mk $target
	}

safeinstallall:V:
	for (i in $LIBS) @{
		cd $i
		mk installall
	}
	for (i in $PROGS) @{
		cd $i
		mk safeinstallall
	}
