</$objtype/mkfile
<../mkupas

TARG=fs

OFILES=\
	cache.$O\
	fs.$O\
	header.$O\
	idx.$O\
	imap.$O\
	mbox.$O\
	mdir.$O\
	mtree.$O\
	plan9.$O\
	pop3.$O\
	remove.$O\
	rename.$O\
	strtotm.$O\
	tls.$O\

LIB=../common/libcommon.a$O\

HFILES= ../common/common.h\
	dat.h

UPDATE=\
	mkfile\
	$HFILES\
	${TARG:%=%.c}\
	${OFILES:%.$O=%.c}\

</sys/src/cmd/mkone
CFLAGS=$CFLAGS  -I../common

acid:V:
	$CC -a $CFLAGS fs.c>a$O
