objtype=spim
</$objtype/mkfile

LIB=/$objtype/lib/libsec.a
FILES=\
	md5block\
	sha1block\

HFILES=/sys/include/libsec.h

SFILES=${FILES:%=%.s}

OFILES=${FILES:%=%.$O}

%.$O:	../mips/%.s
	$AS -I../mips $AFLAGS ../mips/$stem.s

</sys/src/cmd/mksyslib
