</$objtype/mkfile

TARG=gefs
BIN=/$objtype/bin
OFILES=\
	blk.$O\
	cache.$O\
	check.$O\
	cons.$O\
	ctl.$O\
	dump.$O\
	error.$O\
	fs.$O\
	fuzz.$O\
	hash.$O\
	load.$O\
	main.$O\
	pack.$O\
	ream.$O\
	snap.$O\
	tree.$O\
	user.$O\

HFILES=\
	dat.h\
	fns.h\

</sys/src/cmd/mkone
