none:VQ:
	echo usage: mk all, install, installall, cmd, cmd.install, lib, lib.install

all clean nuke install installall:V:
	mk lib.$target
	mk cmd.$target
	mk 9src.$target

lib.%:V:
	cd lib
	mk $stem

lib.clean:V:
	cd lib
	rm -f .mk.$objtype
	mk clean

lib.nuke:V:
	cd lib
	rm -f .mk.$objtype
	mk nuke

cmd.%:V:
	cd cmd
	mk $stem

9src.%:V:
	cd 9src
	mk $stem
