</$objtype/mkfile

OFILES=

TARG=\
	bzip2\
	bunzip2\

HFILES=\
	lib/os.h\
	lib/bzlib.h\
	lib/plan9.h\

LIB=lib/libbzip2.a$O

BIN=/$objtype/bin
</sys/src/cmd/mkmany

CFLAGS=$CFLAGS -p -DPLAN9 -Ilib

bzip2recover.$O: bzip2recover.c
	pcc -D_POSIX_SOURCE -D_BSD_EXTENSION -c bzip2recover.c

clean:V:
	rm -f *.[$OS] y.tab.? y.debug y.output [$OS].* $TARG *.rb2 *.tst
	@{cd lib; mk clean}

lib/libbzip2.a$O:
	@{cd lib; mk}
