</$objtype/mkfile

TARG=serial
OFILES=ftdi.$O serial.$O prolific.$O ucons.$O
HFILES=\
	../lib/usb.h\
	ftdi.h\
	prolific.h\
	serial.h\
	ucons.h\

LIB=../lib/usb.a$O

BIN=/$objtype/bin/nusb

UPDATE=\
	mkfile\
	$HFILES\
	${OFILES:%.$O=%.c}\

</sys/src/cmd/mkone

CFLAGS=-I../lib $CFLAGS
