</$objtype/mkfile

TEST=\
	date\
	pow\
	runebreak\
	runenorm\
	strchr\

</sys/src/cmd/mktest

/lib/ucd/%:
	cd /lib/ucd && mk $stem

runebreak.test:	/lib/ucd/GraphemeBreakTest.txt /lib/ucd/WordBreakTest.txt
runenorm.test: /lib/ucd/NormalizationTest.txt
