</$objtype/mkfile

DIRS=9 ap auth bio bsd bz2 draw fmt l mp net sec utf v z

none:V:
	echo mk all, install, installall, clean, or nuke

all clean nuke install installall:V:
	for (i in $DIRS) @{
		cd $i
		mk $target
	}
