</$objtype/mkfile

DIRS=z `{ls -l | sed '/^d/!d; s/.* //; /\./d'}

none:V:
	echo mk all, install, installall, clean, or nuke

all clean nuke install installall:V:
	for (i in $DIRS) @{
		cd $i
		mk $target
	}
