void	change(File *);
void	cmdprint(char *, ...);
void	docmd(char *);
void*	emalloc(ulong);
void	filinit(File *, char *);
void	filredraw(File *);
char*	filtitle(File *, char *, char *);
int	filtitlelen(File *);
Pal*	findpal(char *, char *, int);
Ident	getident(int);
int	identcmp(Ident*, Ident *);
void	initwin(void);
Pal*	newpal(char *);
Spr*	newspr(char *);
Win*	newwin(int, Rectangle, File *);
Win*	newwinsel(int, Mousectl *, File *);
void	paldraw(Win *);
void	palset(Pal *, int, u32int);
void	palsize(Pal *, int, int);
void	putfil(File *);
void	putident(Ident);
void	putpal(Pal *);
void	putspr(Spr *);
int	quit(void);
int	readpal(Pal *, Biobuf *);
int	readspr(Spr *, Biobuf *);
void	resize(void);
void	setfocus(Win *);
void	sprsize(Spr *, int, int, int);
int	tline(Biobuf *, char **, char **, int);
void	winclick(Mousectl *);
void	winclose(Win *);
void	winresize(Win *, Mousectl *);
Win*	winsel(Mousectl*, int);
void	winwrite(Win *, char *);
void	winzerox(Win *, Mousectl *);
int	writepal(Pal *, char *);
int	writespr(Spr *, char *);
