</sys/doc/fonts

8½.ps:D:	8½.ms fig1.ps
	{echo $FONTS; cat 8½.ms} | tbl | troff -ms -mpictures -mnihongo | lp -dstdout >8½.ps
	../cleanps 8½.ps

8½.html:D: 8½.ms
	tbl 8½.ms | htmlroff -ms -mhtml >8½.html

%.pdf:D:	%.ps
	cat ../docfonts $stem.ps >_$stem.ps
	# distill _$stem.ps && mv _$stem.pdf $stem.pdf
	ps2pdf _$stem.ps $stem.pdf && rm -f _$stem.ps
