</$objtype/mkfile

SUPPORTED_OBJS=\
	386\
	amd64\
	arm\
	arm64\
	mips\

LIBS=\
	lib9p\
	libString\
	libaml\
	libauth\
	libauthsrv\
	libavl\
	libbin\
	libbio\
	libc\
	libcomplete\
	libcontrol\
	libdisk\
	libdraw\
	libflate\
	libfis\
	libframe\
	libgeometry\
	libhtml\
	libhttpd\
	libip\
	liblex\
	libjson\
	libmach\
	libmemdraw\
	libmemlayer\
	libmp\
	libndb\
	libplumb\
	libregexp\
	libsat\
	libscribble\
	libsec\
	libstdio\
	libsunrpc\
	libthread\
	libttf\
	libventi\
	libdtracy\


CMDS=cmd\
	games\

SUBSYS=ape\
	/acme\

none:VQ:
	echo mk all, install, clean, nuke, release, kernels, or libs

all install clean nuke:VQ:
	date
	if (~ $objtype $SUPPORTED_OBJS) {
		for (i in $LIBS $SUBSYS $CMDS) @{
			cd $i
			mk $target
		}
	}
	if not
		echo $objtype arch not supported by 9front >[1=2]
	date

installall:V:
	echo "installall not supported"

release:V:
	if (~ $objtype $SUPPORTED_OBJS) {
		mk nuke
		rm -f /$objtype/lib/ape/*.a
		rm -f /$objtype/lib/*.a
		mk install
		mk clean
	}
	if not
		echo $objtype architecture not supported >[1=2]

kernels:V:
	for (i in 9 boot) @{
		cd $i
		mk clean
		mk install
		mk clean
	}

libs:V:
	date
	for (i in $LIBS) @{
		cd $i
		mk clean
		mk install
		mk clean
	}
	date

cleanlibs:V:
	for (i in $LIBS) @{
		cd $i
		mk clean
	}

updatelibs:V:
	for (i in $LIBS) @{
		cd $i
		mk update
	}
