</$objtype/mkfile

TARG=\
	ml\
	mlowner\
	mlmgr\

LIB=../common/libcommon.a$O

OFILES=common.$O

HFILES=\
	../common/common.h\
	../common/sys.h\
	dat.h\
	../smtp/rfc822.tab.h\

</sys/src/cmd/mkmany
<../mkupas
CFLAGS=$CFLAGS -I../common

$O.ml: ../smtp/rfc822.tab.$O
$O.mlowner: ../smtp/rfc822.tab.$O

../smtp/rfc822.tab.h ../smtp/rfc822.tab.$O: ../smtp/rfc822.y
	cd ../smtp && mk rfc822.tab.h rfc822.tab.$O
