</$objtype/mkfile

LIB=/$objtype/lib/libgeometry.a

OFILES=\
	point.$O\
	matrix.$O\
	quaternion.$O\
	rframe.$O\
	triangle.$O\
	utils.$O\
	fmt.$O\

HFILES=\
	/sys/include/geometry.h

UPDATE=\
	mkfile\
	$HFILES\
	${OFILES:%.$O=%.c}\

</sys/src/cmd/mksyslib
