</$objtype/mkfile
<../mkupas

OFILES=\
	auth.$O\
	copy.$O\
	csquery.$O\
	date.$O\
	debug.$O\
	fetch.$O\
	folder.$O\
	fsenc.$O\
	fstree.$O\
	imp.$O\
	imap4d.$O\
	list.$O\
	mbox.$O\
	msg.$O\
	mutf7.$O\
	nodes.$O\
	print.$O\
	quota.$O\
	search.$O\
	store.$O\
	utils.$O\

HFILES=imap4d.h\
	fns.h\

TARG=imap4d
UPDATE=\
	mkfile\
	$HFILES\
	${OFILES:%.$O=%.c}\

</sys/src/cmd/mkone
