objtype=arm
</$objtype/mkfile

LIB=/$objtype/lib/libmp.a
SFILES=mpvecdigmuladd.s mpvecdigmulsub.s mpvecadd.s mpvecsub.s

HFILES=/$objtype/include/u.h /sys/include/mp.h ../port/dat.h

OFILES=${SFILES:%.s=%.$O}

UPDATE=mkfile\
	$HFILES\
	$SFILES\

</sys/src/cmd/mksyslib
