objtype=spim
</$objtype/mkfile

LIB=/$objtype/lib/libmp.a
SFILES=\
	mpvecadd.s\
	mpvecsub.s\
	mpvecdigmuladd.s\
	mpvecdigmulsub.s\
#	mpdigdiv.s\

HFILES=/$objtype/include/u.h /sys/include/mp.h ../port/dat.h

OFILES=${SFILES:%.s=%.$O}

%.$O:	../mips/%.s
	$AS -I../mips $AFLAGS ../mips/$stem.s

</sys/src/cmd/mksyslib
