</$cputype/mkfile

TEST=\
	add\
	basic\
	diff\
	export\
	ftype\
	lca\
	merge\
	noam\
	range\
	rebase

<mktest

$cputype.git:
	@{mkdir -p $target; rfork n; bind -c $target /$objtype/bin/git; cd .. && objtype=$cputype mk install}

test:V:	$cputype.git

clean:V:
	rm -f *.[$OS] *.out *.a[$OS] y.tab.? lex.yy.c y.debug y.output [$OS].??* $TARG
	rm -fr scratch $cputype.git
