</$objtype/mkfile

BIN=/$objtype/bin
TARG=vmx
CLEANFILES=$O.vmxgdb
HFILES=dat.h fns.h
OFILES=\
	vmx.$O \
	ksetup.$O \
	exith.$O \
	io.$O \
	ide.$O \
	vga.$O \
	pci.$O \
	virtio.$O \
	vesa.$O \
	9p.$O \
	x86.$O \
	nanosec.$O \

</sys/src/cmd/mkone

default:V:	all

all:V:	$O.out $O.vmxgdb

install:V:	$BIN/vmxgdb

$BIN/vmxgdb: $O.vmxgdb
	cp $prereq $BIN/vmxgdb

$O.vmxgdb: vmxgdb.$O
	$LD $LDFLAGS -o $target $prereq
