</$objtype/mkfile
<../mkinc

CFLAGS = -DDEFAULTMAP="/sys/lib/music/map"
TARG = jukefs
BIN = /$objtype/bin/games

CFILES=\
	catset.c\
	fs.c\
	parse.c\
	print.c\
	search.c\
	server.c\

OFILES = ${CFILES:%.c=%.$O}

</sys/src/cmd/mkone
