APE=/sys/src/ape
<$APE/config
LIB=/$objtype/lib/ape/libap.a
OFILES=\
	_seek.$O\
	getfcr.$O\
	lock.$O\
	main9.$O\
	notetramp.$O\
	setjmp.$O\
	tas.$O\

</sys/src/cmd/mksyslib

CFLAGS=-c -D_POSIX_SOURCE -D_PLAN9_SOURCE

