</$objtype/mkfile

TARG=scanmail\
	testscan

OFILES=	common.$O

HFILES=	spam.h\
	../common/sys.h\

LIB=	../common/libcommon.a$O\

UPDATE=\
	mkfile\
	$HFILES\
	${OFILES:%.$O=%.c}\
	${TARG:%=%.c}\

</sys/src/cmd/mkmany
CFLAGS=$CFLAGS -I../common

<../mkupas

scanmail.$O:	scanmail.c
	$CC $CFLAGS scanmail.c
