</$cputype/mkfile
APE=/sys/src/ape
<$APE/config

LIB=../libpython.a$O

OFILES=\
	Python-ast.$O\
	asdl.$O\
	ast.$O\
	bltinmodule.$O\
	ceval.$O\
	codecs.$O\
	compile.$O\
	dynload_stub.$O\
	errors.$O\
#	fmod.$O\
	frozen.$O\
	frozenmain.$O\
	future.$O\
	getargs.$O\
	getcompiler.$O\
	getcopyright.$O\
	getmtime.$O\
	getopt.$O\
	getplatform.$O\
	getversion.$O\
	import.$O\
	importdl.$O\
	marshal.$O\
	modsupport.$O\
	mysnprintf.$O\
	mystrtoul.$O\
	pyarena.$O\
	pyfpe.$O\
	pystate.$O\
	pystrtod.$O\
	pythonrun.$O\
#	sigcheck.$O\
	structmember.$O\
	symtable.$O\
	sysmodule.$O\
	thread.$O\
	traceback.$O\
	graminit.$O\

CLEANFILES=graminit.c graminit.h

</sys/src/cmd/mksyslib

CFLAGS=-c -I.. -I../Include -DT$objtype -DPy_BUILD_CORE -DNDEBUG

ast.$O future.$O:	../Include/graminit.h

../Include/graminit.h:	graminit.h
	cp graminit.h ../Include/graminit.h

graminit.c graminit.h:D: ../Grammar/Grammar ../Parser/pgen.$cputype
	../Parser/pgen.$cputype ../Grammar/Grammar graminit.h graminit.c

../Parser/pgen.$cputype:D:
	@{cd ../Parser && objtype=$cputype mk pgen.$cputype}
