APE=/sys/src/ape
<$APE/config

CFLAGS=-FVwN
BIN=/$objtype/bin

TARG=\
	python\

OFILES=\
	config.$O\
	plan9.$O\
	libpython.a$O\
	libextra.a$O\

LIBDIRS=Python Parser Modules Objects Extra

</sys/src/cmd/mkone

CFLAGS=-c -I. -IInclude -DT$objtype -DPy_BUILD_CORE -DNDEBUG

libpython.a$O libextra.a$O:D:
	for (i in $LIBDIRS) @{cd $i && mk}

config.c:D: Modules/config Extra/config mkconfig
	./mkconfig Modules/config Extra/config > $target

Extra/config:D:
	du -a Extra | awk '/\.c$/{print $2}' | sed 's!.*/!!g; s!\.c$!!g' > $target

clean nuke:V:
	for(i in $LIBDIRS) @{cd $i && mk $target}
	rm -f *.[$OS] [$OS].out y.tab.? y.debug y.output $OFILES
	rm -f libpython.a[$OS] libextra.a[$OS] /$objtype/lib/ape/libpython.a
	rm -f config.c Extra/config
