void *emalloc(ulong);
Image *rgb(u32int);
Poly *mkpoly(int, ...);
Poly *polydup(Poly *);
void polytrans(Poly *, Poly *, double, double, double);
void polydraw(Poly *, Image *, Image *, Image *);
void polybbox(Poly *, Rectangle *);
void polyfix(Poly *);
Obj *mkobj(ObjT *);
Obj *objdup(Obj *);
void objcat(Obj *, Obj *);
Vec vecadd(Vec, Vec);
Vec vecsub(Vec, Vec);
Vec vecmul(Vec, double);
Vec vecnorm(Vec);
double vecdist(Vec, Vec);
double vecdot(Vec, Vec);
Vec vecnormal(Vec);
int objcoll(Obj *, Obj *);
void freeobj(Obj *);
void objexcise(Obj *);
void addtray(ObjT *, ...);
void physstep(void);
int hinged(Obj *, Obj *);
void copyhinges(Obj *, Obj *);
