</$objtype/mkfile

DIRS=port $CPUS

default:V:	all

install clean all:V:
	for(i in port $objtype)@{
		echo $i
		cd $i
		mk $MKFLAGS $target
	}

nuke:V: clean
	rm -f /$objtype/lib/libmp.a

update:V:
	for(i in port $CPUS)@{
		echo $i
		cd $i
		mk $MKFLAGS $target
	}
	update /386/lib/libmp.a

installall:V:
	for(objtype in $CPUS) mk $MKFLAGS install

everything:V:
	rm -f */*.[$OS]
	for(objtype in 386)@{
		echo $objtype
		mk $MKFLAGS install
	}
	rm -f */*.[$OS]

test.$O: test.c /$objtype/include/u.h /sys/include/mp.h port/dat.h
	$CC -Iport test.c

$O.test: test.$O /$objtype/lib/libmp.a
	$LD -o $O.test test.$O

bigtest.$O: bigtest.c /$objtype/include/u.h /sys/include/mp.h port/dat.h
	$CC -Iport bigtest.c

$O.bigtest: bigtest.$O /$objtype/lib/libmp.a
	$LD -o $O.bigtest bigtest.$O

allout:
	objtype=arm; mk; mk 5.test 5.bigtest
	objtype=amd64; mk; mk 6.test 6.bigtest
	objtype=386; mk; mk 8.test 8.bigtest

cleanout:
	rm -f [568].* *.[568]
